# SmoothTP Configuration

# Sound settings
# Set to false if you don't want the enderman-like teleport sound
play-sound: true

# Animation settings
# GTA is the GTA Online-style animation with raising/falling
animation-type: GTA

# Debug mode (additional logging)
# Useful for troubleshooting teleport issues
debug: false

# Message shown when a player teleports (leave empty for no message)
teleport-message: ""

# GTA-style animation settings (durations in ticks, 20 ticks = 1 second)
gta:
  # The duration of the raising up animation
  up-duration: 40
  
  # The duration between the x-z translate animation and the previous animation
  fade-in-duration: 20
  
  # The duration of the x-z translate animation
  stay-duration: 20
  
  # The duration between the x-z translate animation and the next animation
  fade-out-duration: 40
  
  # The duration of the falling down animation
  down-duration: 40
  
  # The idle duration after the falling down animation
  down-stay-duration: 20
  
  # The blocks to raise up when teleporting
  up-offset: 100.0
