name: SmoothTP
main: com.youssgm3o8.smoothtp.Main
version: 1.0.0
api: ["1.0.0"]
description: Provides smooth teleportation animations including GTA Online style
author: YoussGm3o8

commands:
  smoothtp:
    description: Reload the SmoothTP configuration
    usage: "/smoothtp reload"
    permission: smoothtp.reload
    aliases: [stp]

permissions:
  smoothtp.reload:
    description: Allows reloading the SmoothTP configuration
    default: op